name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
      
    - name: Cache
      uses: actions/cache@v3.0.11
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        # An explicit key for restoring and saving the cache
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/buildSrc/**/*.kt') }}
        # An ordered list of keys to use for restoring stale cache if no cache hit occurred for key. Note `cache-hit` returns false in this case.
        restore-keys:  |
          ${{ runner.os }}-gradle-
          
    - name: Grant execute permission for gradlew
      run: chmod -x gradlew
      
    - name: Run unit tests
      run: ./gradlew testDebugUnitTest
      
      

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
